In [7]:
import requests
import json
import prettytable

In [ ]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['LASST010000000000003','LASST020000000000003', 'LASST040000000000003',
                                'LASST050000000000003','LASST060000000000003','LASST080000000000003',
                                'LASST090000000000003','LASST100000000000003','LASST110000000000003',
                                'LASST120000000000003','LASST130000000000003','LASST150000000000003',
                                'LASST160000000000003','LASST170000000000003','LASST180000000000003',
                                'LASST180000000000003','LASST190000000000003','LASST200000000000003',
                                'LASST210000000000003','LASST220000000000003','LASST230000000000003',
                                'LASST240000000000003','LASST250000000000003','LASST260000000000003',
                                'LASST270000000000003','LASST280000000000003','LASST280000000000003',
                                'LASST290000000000003'],"startyear":"2009", "endyear":"2018"})

# UNEMPLOYEMNT RATE BY STATE, SEASONALLY ADJUSTED:
# 01 Alabama, 02 Alaska, 04 Arizona, 05 Arkansas, 06 California, 08 Colorado, 09 Connecticut,
# 10 Delaware, 11 District of Columbia, 12 Florida, 13 Georgia, 15 Hawaii, 16 Idaho,
# 17 Illinois, 18 Indiana, 19 Iowa, 20 Kansas, 21 Kentucky, 22 Louisiana, 23 Maine, 
# 24 Maryland, 25 Massachusetts, 26 Michigan, 27 Minnesota, 28 Mississippi

p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + 'b' + '.txt','w')
    output.write (x.get_string())
    output.close()

In [6]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['LASST300000000000003','LASST310000000000003','LASST320000000000003',
                                'LASST330000000000003','LASST340000000000003','LASST350000000000003',
                                'LASST360000000000003','LASST370000000000003','LASST380000000000003',
                                'LASST390000000000003','LASST400000000000003','LASST410000000000003',
                                'LASST420000000000003','LASST440000000000003','LASST450000000000003',
                                'LASST460000000000003','LASST470000000000003','LASST480000000000003',
                                'LASST490000000000003','LASST500000000000003','LASST510000000000003',
                                'LASST530000000000003','LASST540000000000003','LASST550000000000003',
                                'LASST560000000000003'],"startyear":"2009", "endyear":"2018"})

# UNEMPLOYEMNT RATE BY STATE, SEASONALLY ADJUSTED:
# 29 Missouri, 30 Montana, 31 Nebraska, 32 Nevada, 33 New Hampshire, 34 New Jersey, 35 New Mexico, 
# 36 New York, 37 North Carolina, 38 North Dakota, 39 Ohio, 40 Oklahoma, 41 Oregon, 
# 42 Pennsylvania, 44 Rhode Island, 45 South Carolina, 46 South Dakota, 47 Tennessee, 
# 48 Texas, 49 Utah, 50 Vermont, 51 Virginia, 53 Washington, 54 West Virginia, 
# 55 Wisconsin, 56 Wyoming

p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + 'b' + '.txt','w')
    output.write (x.get_string())
    output.close()

In [5]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['JTU00000000LDR','JTU000000MWLDR','JTU000000NELDR','JTU000000SOLDR',
                                'JTU000000WELDR'],"startyear":"1999", "endyear":"2018"})

# RATE OF LAYOFFS AND DISCHARGES, NON-SEASONALLY ADJUSTED:
#    00 = TOTAL US, MW = MIDWEST, NE = NORTHEAST, SO = SOUTH, WE = WEST

p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + '.txt','w')
    output.write (x.get_string())
    output.close()

In [10]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['SAS0800002000011'],"startyear":"1999", "endyear":"2018"})

# 'SMU02000000000000049','SMU04000000000000049','SMU05000000000000049','SMU06000000000000049'
# 01 Alabama, 02 Alaska, 04 Arizona, 05 Arkansas, 06 California, 08 Colorado, 09 Connecticut,
# 10 Delaware, 11 District of Columbia, 12 Florida, 13 Georgia, 15 Hawaii, 16 Idaho,
# 17 Illinois, 18 Indiana, 19 Iowa, 20 Kansas, 21 Kentucky, 22 Louisiana, 23 Maine, 
# 24 Maryland, 25 Massachusetts, 26 Michigan, 27 Minnesota, 28 Mississippi, 29 Missouri, 
# 30 Montana, 31 Nebraska, 32 Nevada, 33 New Hampshire, 34 New Jersey, 35 New Mexico, 
# 36 New York, 37 North Carolina, 38 North Dakota, 39 Ohio, 40 Oklahoma, 41 Oregon, 
# 42 Pennsylvania, 44 Rhode Island, 45 South Carolina, 46 South Dakota, 47 Tennessee, 
# 48 Texas, 49 Utah, 50 Vermont, 51 Virginia, 53 Washington, 54 West Virginia, 
# 55 Wisconsin, 56 Wyoming, 72 Puerto Rico

# OEUM001018000000000000008  hourly mean wage for all occupations in all industries 
# in Abilene, TX

# NON-SEASONALLY ADJUSTED:

# SA
# S
# 000000 total non-farm
# Series ID    SMUXX000000000000049
# where XX = state id
# 	Positions       Value           Field Name
# 	1-2             SM              Prefix
# 	3               U               Seasonal Adjustment Code
# 	4-5             19              State Code
# 	6-10            19780           Area Code
# 	11-18           20238000        SuperSector and Industry Code
# 	19-20           01             	Data Type Code

#                                 45	INDEXES OF AGGREGATE WEEKLY PAYROLLS, 1982=100
#                                 49	AVERAGE HOURLY EARNINGS, 1982 DOLLARS

    
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + '.txt','w')
    output.write (x.get_string())
    output.close()